name: brewery
description: Mobile frontend to Homebrew formulae API

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_linkify: ^5.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  http: ^0.13.0
  keybinder: ^1.0.0
  keyboard_dismisser: ^2.0.0
  path_provider: ^2.0.1
  rxdart: ^0.26.0
  shared_preferences: ^2.0.3
  url_launcher: ^6.0.2
  url_strategy: ^0.2.0

dev_dependencies:
  bloc_test: ^8.0.0-nullsafety.1
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  pedantic: ^1.11.0
  # flutter_launcher_name: "^0.0.1" # not compatible for now (null safety)

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: icons/icon.png

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#2F2A25"
  image: icons/icon-splash.png

# flutter pub run flutter_launcher_name:main
flutter_launcher_name:
  name: Brewery

flutter:
  uses-material-design: true
  assets:
    - icons/icon.svg
