name: brewery
description: Mobile frontend to Homebrew formulae API

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: "^0.12.2"
  path_provider: "^1.6.27"
  flutter_svg: "^0.19.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
  flutter_native_splash: "^0.2.10"
  flutter_launcher_name: "^0.0.1"

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/icon.png

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#2F2A25"
  image: assets/icons/icon-splash.png

# flutter pub run flutter_launcher_name:main
flutter_launcher_name:
  name: Brewery

flutter:
  uses-material-design: true

