/// Flutter icons BreweryIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BreweryIcons
///      fonts:
///       - asset: fonts/BreweryIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class BreweryIcons {
  BreweryIcons._();

  static const _kFontFam = 'BreweryIcons';
  static const String _kFontPkg = null;

  static const IconData wine_cask =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recipe_book =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
