name: CD

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: build/web
        env:
          GITHUB_TOKEN: ${{github.token}}
