name: CD

on:
  workflow_run:
    workflows:
      - CI
    branches:
      - master
    types:
      - completed

jobs:
  cd:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build web --release --web-renderer canvaskit
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: build/web
        env:
          GITHUB_TOKEN: ${{github.token}}
