name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{runner.os}}-flutter-stable-
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - uses: actions/cache@v2
        with:
          path: ${{env.FLUTTER_HOME}}/.pub-cache
          key: ${{runner.os}}-pub-${{hashFiles('**/pubspec.lock')}}
          restore-keys: ${{runner.os}}-pub-
      - run: flutter pub get
      - uses: actions/cache@v2
        with:
          path: build
          key: ${{runner.os}}-build-
      - run: flutter build apk
      - uses: actions/upload-artifact@v2
        with:
          name: apk
          path: build/app/outputs/apk/release/app-release.apk
